-keepclass class * { @at.sunilson.unidirectionalviewmodel.* *; }
-keepclassmembers class * { @at.sunilson.unidirectionalviewmodel.* *; }
-keepclasseswithmembers class * { @at.sunilson.unidirectionalviewmodel.* *; }