-keep @at.sunilson.unidirectionalviewmodel.savedstate.PersistableState public class * { *; }
-keepclassmembers,includedescriptorclasses @at.sunilson.unidirectionalviewmodel.savedstate.PersistableState class * { *; }
-keep class kotlin.Metadata { *; }
-keepattributes *Annotation*, Signature
